name: Reminder
on:
  schedule:
    - cron: 34 3 * * *
  workflow_dispatch: null
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - id: generate
        run: python3 scripts/do_the_thing.py
      - uses: gr2m/set-cron-schedule-action@v2
        with:
          token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
          cron: ${{ steps.generate.outputs.cron_schedule }}
          workflow: my-workflow.yml
          message: set next cron schedule dynamically
